### ISSUE TITLE
local build rsqrt declaration mismatch

### ISSUE THREAD

**Issue by jwkvam** [EnzymeAD/Reactant.jl#2015]
I haven't spent a lot of time trying to debug this yet.

I'm trying to do a local build by running
```
julia -O0 --color=yes --project build_local.jl --backend cuda --jobs 20 --extraopt '--strip=never' --copt -g --extraopt '--linkopt=-fuse-ld=lld'
```
in the `deps` subdirectory.

I see this error:
```
/usr/include/bits/mathcalls.h:206:15: error: exception specification in declaration does not match previous declaration
  206 | extern double rsqrt(double __x) noexcept(true); extern double __rsqrt(double __x) noexcept(true);
      |               ^
external/cuda_crt/include/crt/math_functions.h:629:15: note: previous declaration is here
  629 | extern double rsqrt(double x);
      |               ^
/usr/include/bits/mathcalls.h:206:14: error: exception specification in declaration does not match previous declaration
  206 | extern float rsqrtf(float __x) noexcept(true); extern float __rsqrtf(float __x) noexcept(true);
      |              ^
external/cuda_crt/include/crt/math_functions.h:653:14: note: previous declaration is here
  653 | extern float rsqrtf(float x);
      |              ^
2 errors generated.
Target //:libReactantExtra.so failed to build
```

Some basic system stats:
- Arch
- gcc: 15.2.1
- cuda: 13.1
- julia: 1.12.3 (which I know is unsupported)

AFAICT my local cuda install declares rsqrt with noexcept. So I'm trying to figure out where bazel is pulling cuda from.

**Comment by wsmoses** [comment]
the julia version here shouldn't matter for the build.

quick question for sake of understanding, what is your intended use case from the local build of the jll (in contrast to using the prebuilt so).

**Comment by jwkvam** [comment]
This may be misguided, but I was trying to see if I could get a little farther trying to get Lux working on Julia 1.12 with Reactant. I was curious about trying to understand a bit deeper what's going on.

This would be the "Opaque closure with no source at all" error.

**Comment by giordano** [comment]
I seem to remember this is a problem with CUDA and newer glibc versions which Nvidia is refusing to fix at the moment. Nothing we can do about this.

**Comment by giordano** [comment]
Yes, I remembered correctly: https://stackoverflow.com/a/79594409

**Comment by wsmoses** [comment]
for content @jwkvam 1.12 support [or any julia versoin for that matter] doesn't depend on the jll. The jll works across all versions. 1.12 is mostly fine, but there are some weird issues with opaque closures that have popped up and need debugging (e.g. look at the code from within https://github.com/EnzymeAD/Reactant.jl/issues/2012#issue-3755886182 except on 1.12)

**Comment by jwkvam** [comment]
Thanks for the quick responses. It seems that your fix addressed the issue that I was facing.
