### ISSUE TITLE
'llvm.call' op incorrect number of operands in 1.12

### ISSUE THREAD

**Issue by dkytezab** [EnzymeAD/Reactant.jl#2701]
cc @Pangoraw. Works in 1.11
```julia
using CUDA, Reactant, KernelAbstractions
using Reactant: ConcreteRNumber
using Adapt: Adapt

mutable struct Clock{TT, S}
    time :: TT
    stage :: S
end

Adapt.adapt_structure(to, clock::Clock) = (time          = clock.time,
                                           stage         = clock.stage)

@kernel function _fill!(c, args)
    i = @index(Global)
    @inbounds c[i] = c[i]
end

N = 16
c = Reactant.to_rarray(zeros(N))
clock = Clock(ConcreteRNumber(0.0), 1)

function loss(c, clock)
    backend = KernelAbstractions.get_backend(c)
    _fill!(backend)(c, clock; ndrange=size(c))
    KernelAbstractions.synchronize(backend)
    return 0.0
end

compiled = Reactant.@compile raise=true raise_first=true loss(c, clock)
```
```
error: 'llvm.call' op incorrect number of operands (3) for callee (expecting: 4)
┌ Error: Compilation failed, MLIR module written to /var/folders/km/c7cykv9x5s955_48nqv3f4cm0000gn/T/reactant_QV60I9/module_000_nxc9_post_raise_triton_custom_call_pm.mlir
└ @ Reactant.MLIR.IR ~/Aeolus2/Reactant.jl/src/mlir/IR/Pass.jl:146
```
